# Generated by Django 5.1.1 on 2024-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0002_remove_account_account_type_remove_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
